### ISSUE TITLE
findutils build is broken

### ISSUE THREAD

**Issue by vaskas** [berryamin/berrymuch#10]
```
» ./build.sh
Building findutils
Cloning into 'findutils'...
remote: Counting objects: 577, done.
remote: Compressing objects: 100% (345/345), done.
remote: Total 577 (delta 48), reused 417 (delta 31)
Receiving objects: 100% (577/577), 630.71 KiB | 293.00 KiB/s, done.
Resolving deltas: 100% (48/48), done.
Checking connectivity... done.
fatal: reference is not a tree: 003c8e6e3734c35c8a5d639528548181f0fada7f

**Comment by berryamin** [comment]
Looks like a pure git issue ..
You mean findutils from master branch ?

**Comment by berryamin** [comment]
<pre>
+ cd findutils
+ git checkout 003c8e6e3734c35c8a5d639528548181f0fada7f
fatal: reference is not a tree: 003c8e6e3734c35c8a5d639528548181f0fada7f
</pre>

**Comment by vaskas** [comment]
Yes we have this issue in master. Wonder why we ever needed that particular revision of findutils. Would be great to convert it to the latest version. This would need some patching to mock the mounts lookup from what I can see.
