### ISSUE TITLE
Suggestion: enable GitHub Wiki for the repository

### ISSUE THREAD

**Issue by vaskas** [berryamin/berrymuch#17]
A wiki would be a great way to maintain the documentation, tips and tricks etc. including:

1. Current detailed project status
2. Cross-compilation tips and tricks

I would also like us to start consolidating information scattered around the forums - there are nuggets that are hard to find unless you are reading every single page sometimes.

**Comment by berryamin** [comment]
+1 to consolidate informations from the forums

**Comment by berryamin** [comment]
Wiki Opened :)

https://github.com/berryamin/berrymuch/wiki
