### ISSUE TITLE
any ssl lib compiled successfully ?

### ISSUE THREAD

**Issue by berryamin** [berryamin/berrymuch#4]
Hi,
    many applications require an ssl library ..
So far I've not been able to compile nettle, openssl nor wolfssh for bb10. Any inputs out there ?

**Comment by yamsergey** [comment]
But we have OpenSSL in bootstrap. As I remember it was working just fine. Can you describe your problem?

**Comment by berryamin** [comment]
On my mac, openssl-1.0.2o compilation fails with:

make[2]: Entering directory `/Users/testuser/bb/playbook-dev-tools/work/openssl-1.0.2o/apps'
( :; LIBDEPS="${LIBDEPS:--L.. -lssl  -L.. -lcrypto -lsocket }"; LDCMD="${LDCMD:-arm-unknown-nto-qnx8.0.0eabi-gcc}"; LDFLAGS="${LDFLAGS:--DOPENSSL_THREADS  -DNO_SYSLOG }"; LIBPATH=`for x in $LIBDEPS; do echo $x; done | sed -e 's/^ *-L//;t' -e d | uniq`; LIBPATH=`echo $LIBPATH | sed -e 's/ /:/g'`; LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH ${LDCMD} ${LDFLAGS} -o ${APPNAME:=openssl} openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o ${LIBDEPS} )
eyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o ${LIBDEPS} )
openssl.o: In function `main':
openssl.c:(.text+0x17e): undefined reference to `BIO_s_file'
openssl.c:(.text+0x186): undefined reference to `BIO_new'
openssl.c:(.text+0x1c0): undefined reference to `BIO_ctrl'
openssl.c:(.text+0x1f8): undefined reference to `CRYPTO_dbg_get_options'
openssl.c:(.text+0x1fc): undefined reference to `CRYPTO_dbg_get_options'
openssl.c:(.text+0x202): undefined reference to `CRYPTO_dbg_malloc'
openssl.c:(.text+0x206): undefined reference to `CRYPTO_dbg_malloc'
openssl.c:(.text+0x20a): undefined reference to `CRYPTO_dbg_realloc'
openssl.c:(.text+0x20e): undefined reference to `CRYPTO_dbg_realloc'
(...)

I think commit 2b5031a2ff7b03bffa39e8aafbaa90eaa269e59a which introduced openssl-1.0.2o to master, should have been added to a dedicated branch, not master, my mistake.

If you succeed to build on Linux, I'd be very interested to get the package/openssl-1.0.2o.zip

**Comment by vaskas** [comment]
@berryamin I'll dig up the packages when I get home. OpenSSL from bootstrap builds fine for me.

Bigger question is which cross-compilation host platforms we should support. I am a GNU/Linux user myself but am still running a Ubuntu 16.04 32-bit VM for the NDK. With 16.04 still being supported until 2021 (https://ubuntu.com/about/release-cycle) it's a pretty safe option to use. That said I'm going to try upgrading the VM to 18.04 to see if there are any issues.

**Comment by berryamin** [comment]
Ho interesting. Taskwarrior would appreciate openssl support :)

**Comment by vaskas** [comment]
[openssl-1.0.2o.zip](https://github.com/berryamin/berrymuch/files/3975855/openssl-1.0.2o.zip)

**Comment by vaskas** [comment]
FYI Our openssl port now supports shared libraries compilation: https://github.com/berryamin/berrymuch/blob/master/ports/openssl/build.sh - I've used these successfully to enable TLSv1.2 in curl
