### ISSUE TITLE
text mode browser for bb10 .. link2 anytime soon ?

### ISSUE THREAD

**Issue by berryamin** [berryamin/berrymuch#7]
If you want to make "link2 on bb10" happen, please checkout this thread on crackberry,

https://forums.crackberry.com/blackberry-10-os-f269/there-text-only-browser-setting-blackberry-10-os-1176535

and/or the following branch:

https://github.com/berryamin/playbook-dev-tools/tree/add_links2/bootstrap/links2

**Comment by vaskas** [comment]
Closing the issue as we have https://github.com/berryamin/berrymuch/wiki/Wishlist now
